loki:
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h # 7 days
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  service:
    type: ClusterIP
  securityContext:
    runAsUser: 10001
  replicas: 1
