apiVersion: v1
kind: Service
metadata:
  name: "sample-service-nginx"
  labels:
    {{- include "sample-service-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # - port: {{ .Values.service.port }}
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "sample-service-helm.selectorLabels" . | nindent 4 }}
