apiVersion: v1
kind: Service
metadata:
  name: "sample-service-go"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "sample-service-go"
