apiVersion: v1
kind: Service
metadata:
  name: "sample-service-grpc"
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "sample-service-grpc"