apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: myapp:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080